[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "basic_ml_pipeline"
version = "0.1.0"
dependencies = [
    "clickhouse-connect",
    "dagster==1.13.6",
    "dagster-aws==0.29.6",
    "dagster-pipes==1.13.6",
    "dagster-postgres==0.29.6",
    "dagster_shared==1.13.6",
    "numpy",
    "pandas>=2.2,<3",
    "psycopg2-binary",
    "pyarrow",
    "PyYAML",
    "python-dotenv",
    "requests",
    "scikit-learn",
    "SQLAlchemy",
    "tabulate",
]
