apiVersion: v1
kind: Secret
metadata:
  name: dagster-postgres
  namespace: data-platform
type: Opaque
stringData:
  DAGSTER_PG_HOST: "${RDS_HOST}"
  DAGSTER_PG_DB: dagster
  DAGSTER_PG_USER: dagster
  DAGSTER_PG_PASSWORD: "${RDS_PASSWORD}"
