apiVersion: v1
kind: Secret
metadata:
  name: etl-pipeline-secrets
  namespace: data-platform
type: Opaque
stringData:
  secrets.aws.yaml: |
    dbs:
      postgres:
        user: dagster
        password: "${RDS_PASSWORD}"
      clickhouse:
        user: dagster
        password: "${CLICKHOUSE_PASSWORD}"
